---
apiVersion: v1
kind: Pod
metadata:
  name: empms-attendance
  labels: 
    app: empms-attendance 
spec: 
  containers:
    - name: empms-attendance
      image: suyash1610/empms:suyash-attendance
      ports: 
        - containerPort: 8081