---
apiVersion: v1
kind: Pod
metadata:
  name: empms-db
  labels: 
    app: empms-db
spec: 
  containers:
    - name: empms-db
      image: suyash1610/empms:suyash-db
      ports: 
        - containerPort: 3306