---
apiVersion: v1
kind: Pod
metadata:
  name: empms-salary
  labels: 
    app: empms-salary 
spec: 
  containers:
    - name: empms-salary
      image: suyash1610/empms:suyash-salary
      ports: 
        - containerPort: 8082