---
apiVersion: v1
kind: Pod
metadata:
  name: empms-webserver
  labels: 
    app: empms-webserver 
spec: 
  containers:
    - name: empms-webserver
      image: suyash1610/empms:suyash-webserver
      ports: 
        - containerPort: 80
    - name: empms-frontend
      image: suyash1610/empms:suyash-frontend
      ports: 
        - containerPort: 5000