---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: empms-es
  labels:
    app: empms-es
spec:
  replicas: 1
  selector:
    matchLabels:
      app: empms-es
  strategy: {}
  template:
    metadata:
      labels:
        app: empms-es
    spec:
      containers:
      - image: suyash1610/empms:suyash-es
        imagePullPolicy: Always
        name: empms-es
        ports:
        - containerPort: 9200

---
kind: Service
apiVersion: v1
metadata:
  name: empms-es
spec:
  type: ClusterIP
  selector:
    app: empms-es
  ports:
  - protocol: TCP
    port: 9200